package parser

import (
	"testing"
)

func refsOf(t *testing.T, wf *WorkflowFile) []string {
	t.Helper()
	out := make([]string, 0, len(wf.Tools))
	for _, tool := range wf.Tools {
		out = append(out, tool.Reference)
	}
	return out
}

func TestPythonLock_Poetry(t *testing.T) {
	const content = `
# This file is automatically @generated by Poetry.
[[package]]
name = "certifi"
version = "2024.8.30"
description = "Mozilla's CA Bundle."
optional = false
python-versions = ">=3.6"

[[package]]
name = "Jinja2"
version = "3.1.4"
optional = false

[[package]]
name = "zope.interface"
version = "7.0.3"
optional = true

[metadata]
lock-version = "2.0"
`
	p := NewPythonLockParser()
	if !p.Supports("/x/poetry.lock") {
		t.Fatal("poetry.lock must be supported")
	}
	wf, err := p.Parse("poetry.lock", []byte(content))
	if err != nil {
		t.Fatal(err)
	}
	// Names are normalised per PEP 503, and an optional group is still a
	// package that runs in the build.
	want := []string{"certifi@2024.8.30", "jinja2@3.1.4", "zope-interface@7.0.3"}
	got := refsOf(t, wf)
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}
	if wf.Type != "pypi" {
		t.Fatalf("type = %q", wf.Type)
	}
}

func TestPythonLock_UVSkipsTheProjectItself(t *testing.T) {
	const content = `
version = 1
requires-python = ">=3.12"

[[package]]
name = "my-app"
version = "0.1.0"
source = { editable = "." }

[[package]]
name = "httpx"
version = "0.27.2"
source = { registry = "https://pypi.org/simple" }

[[package]]
name = "vendored-thing"
version = "1.0.0"
source = { url = "https://example.invalid/x.whl" }
`
	wf, err := NewPythonLockParser().Parse("uv.lock", []byte(content))
	if err != nil {
		t.Fatal(err)
	}
	got := refsOf(t, wf)
	if len(got) != 1 || got[0] != "httpx@0.27.2" {
		t.Fatalf("got %v, want only httpx", got)
	}
	// The project itself is skipped in silence; what cannot be verified is
	// named rather than dropped, because a baseline's gaps are part of what
	// it means.
	if len(wf.Unsupported) != 1 {
		t.Fatalf("unsupported = %+v", wf.Unsupported)
	}
}

func TestPythonLock_Pipfile(t *testing.T) {
	const content = `{
	  "_meta": {"hash": {"sha256": "abc"}},
	  "default": {
	    "requests": {"hashes": ["sha256:aa"], "version": "==2.32.3"},
	    "urllib3":  {"hashes": ["sha256:bb"], "version": "==2.2.3"},
	    "internal": {"path": "./libs/internal"}
	  },
	  "develop": {
	    "pytest": {"hashes": ["sha256:cc"], "version": "==8.3.3"},
	    "loose":  {"version": ">=1.0"}
	  }
	}`
	wf, err := NewPythonLockParser().Parse("Pipfile.lock", []byte(content))
	if err != nil {
		t.Fatal(err)
	}
	got := refsOf(t, wf)
	want := []string{"pytest@8.3.3", "requests@2.32.3", "urllib3@2.2.3"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}
	if len(wf.Unsupported) != 2 {
		t.Fatalf("unsupported = %+v", wf.Unsupported)
	}
}

// A lock file records the tree; a requirements file records the wish. That
// is the whole reason this parser exists, so it is asserted directly.
func TestPythonLock_CoversMoreThanRequirements(t *testing.T) {
	const requirements = "fastapi==0.115.0\n"
	const lock = `
[[package]]
name = "fastapi"
version = "0.115.0"

[[package]]
name = "starlette"
version = "0.38.6"

[[package]]
name = "pydantic"
version = "2.9.2"

[[package]]
name = "anyio"
version = "4.6.0"
`
	req, err := NewPyPIRequirementsParser().Parse("requirements.txt", []byte(requirements))
	if err != nil {
		t.Fatal(err)
	}
	locked, err := NewPythonLockParser().Parse("poetry.lock", []byte(lock))
	if err != nil {
		t.Fatal(err)
	}
	if len(req.Tools) != 1 {
		t.Fatalf("requirements gave %d", len(req.Tools))
	}
	if len(locked.Tools) <= len(req.Tools) {
		t.Fatalf("the lock file must cover more: %d vs %d", len(locked.Tools), len(req.Tools))
	}
}

func TestPythonLock_RejectsNonsenseWithoutPanicking(t *testing.T) {
	p := NewPythonLockParser()
	for _, name := range []string{"poetry.lock", "uv.lock", "Pipfile.lock"} {
		for _, content := range []string{"", "not a lock file at all", "{", "[[package]"} {
			wf, err := p.Parse(name, []byte(content))
			if err == nil && wf == nil {
				t.Fatalf("%s with %q gave neither result nor error", name, content)
			}
		}
	}
	if p.Supports("requirements.txt") || p.Supports("package-lock.json") {
		t.Fatal("this parser must not claim other files")
	}
}

func TestNormalizePyPIName(t *testing.T) {
	cases := map[string]string{
		"Jinja2":           "jinja2",
		"zope.interface":   "zope-interface",
		"typing_e__x":      "typing-e-x",
		"  Requests  ":     "requests",
		"":                 "",
		"---":              "",
		"ruamel.yaml.clib": "ruamel-yaml-clib",
	}
	for in, want := range cases {
		if got := normalizePyPIName(in); got != want {
			t.Errorf("normalizePyPIName(%q) = %q, want %q", in, got, want)
		}
	}
}
